name: Scaffold-eth Staging Surge Deployer workflow

on:
  push:
    branches: [develop]

jobs:
  deployer-job:
    name: Deployer job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Build React App
        run: |
          cd packages/react-app/ && yarn && CI=false yarn run build
          cp build/index.html build/200.html
        env:
          REACT_APP_SERVER: 'https://moonshot-backend.herokuapp.com/'
          REACT_APP_NETWORK: 'rinkeby'

      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: staging.${{ secrets.domain }}
          project: './packages/react-app/build'
          token: ${{ secrets.surge_token }}
